/**
 * Fetch the game's audio from Kenney's CC0 packs.
 *
 * Same discipline as the icons: the script that downloads the files is the
 * script that records where every one came from, so the credits cannot drift
 * from what actually shipped. Each of the fifteen cues maps to one file from
 * a named pack; the packs are CC0 (public domain), so no attribution is
 * required — it is recorded anyway.
 *
 * Output:
 *   src/ui/sfx/files/<cue>.ogg          — the audio the build imports
 *   src/ui/sfx/audio-credits.json       — pack, original file, licence, date
 *
 * ASSETS_CREDITS.md is regenerated by `npm run icons`, which reads the JSON.
 */
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, copyFileSync, writeFileSync, rmSync } from 'node:fs';
import { get } from 'node:https';

const WORK = '.audio-work';
const OUT = 'src/ui/sfx/files';

const PACKS = {
  'interface-sounds': 'Interface Sounds',
  'impact-sounds': 'Impact Sounds',
  'sci-fi-sounds': 'Sci-Fi Sounds',
  'digital-audio': 'Digital Audio',
  'ui-audio': 'UI Audio',
  'casino-audio': 'Casino Audio',
};

/**
 * cue -> [pack, file inside the pack's Audio/ folder].
 *
 * Build 9 took this from 15 entries to 50. Two packs were added to do it:
 * Casino Audio, which is where a card game's card and chip sounds actually
 * live, and UI Audio for the two interface cues that had to be quieter than
 * anything Interface Sounds offers.
 *
 * Every pack here is CC0 (public domain), so no attribution is required. It
 * is recorded anyway, by the same script that does the downloading, so the
 * credits cannot drift from what shipped.
 */
const CHOICES = {
  // --- interface -----------------------------------------------------------
  'ui-press': ['interface-sounds', 'click_002.ogg'],
  'ui-cancel': ['interface-sounds', 'back_001.ogg'],
  'ui-hover': ['ui-audio', 'rollover1.ogg'],
  'ui-select': ['interface-sounds', 'select_003.ogg'],
  'ui-screen': ['interface-sounds', 'scroll_003.ogg'],
  'ui-modal-open': ['interface-sounds', 'open_001.ogg'],
  'ui-modal-close': ['interface-sounds', 'close_001.ogg'],
  'ui-slider': ['interface-sounds', 'tick_002.ogg'],
  'ui-toggle': ['interface-sounds', 'switch_002.ogg'],
  'ui-refused': ['interface-sounds', 'error_004.ogg'],
  'wallet-connected': ['interface-sounds', 'confirmation_002.ogg'],
  'error-shown': ['interface-sounds', 'error_006.ogg'],

  // --- draft ---------------------------------------------------------------
  'draft-deal': ['casino-audio', 'card-fan-1.ogg'],
  'draft-pick': ['casino-audio', 'card-place-2.ogg'],
  'draft-theirs': ['casino-audio', 'card-slide-3.ogg'],
  'draft-collision': ['casino-audio', 'card-shove-2.ogg'],
  'draft-resolve': ['casino-audio', 'card-slide-7.ogg'],
  'draft-pack': ['casino-audio', 'cards-pack-open-1.ogg'],

  // --- deployment ----------------------------------------------------------
  'ship-pickup': ['impact-sounds', 'impactMetal_light_001.ogg'],
  'ship-rotate': ['interface-sounds', 'switch_005.ogg'],
  'ship-placed': ['impact-sounds', 'impactPlate_medium_000.ogg'],
  'place-refused': ['impact-sounds', 'impactWood_medium_003.ogg'],
  'deploy-auto': ['interface-sounds', 'scratch_002.ogg'],
  'deploy-commit': ['sci-fi-sounds', 'doorClose_001.ogg'],

  // --- combat --------------------------------------------------------------
  'charge-placed': ['interface-sounds', 'click_002.ogg'],
  'card-fired': ['sci-fi-sounds', 'laserLarge_001.ogg'],
  'basic-attack': ['sci-fi-sounds', 'laserRetro_001.ogg'],
  volley: ['sci-fi-sounds', 'thrusterFire_002.ogg'],
  hit: ['sci-fi-sounds', 'impactMetal_002.ogg'],
  miss: ['impact-sounds', 'impactSoft_heavy_001.ogg'],
  'ship-sunk': ['sci-fi-sounds', 'explosionCrunch_002.ogg'],
  'ability-activated': ['digital-audio', 'phaseJump1.ogg'],
  'react-triggered': ['digital-audio', 'zap1.ogg'],
  'charges-stolen': ['casino-audio', 'chips-handle-2.ogg'],
  'prediction-triggered': ['impact-sounds', 'impactBell_heavy_002.ogg'],
  'shot-blocked': ['sci-fi-sounds', 'forceField_001.ogg'],

  // --- the shape of a round ------------------------------------------------
  'match-found': ['digital-audio', 'twoTone1.ogg'],
  'phase-card': ['interface-sounds', 'maximize_003.ogg'],
  'round-start': ['digital-audio', 'threeTone1.ogg'],
  'resolve-step': ['interface-sounds', 'tick_001.ogg'],
  'timer-warning': ['interface-sounds', 'click_005.ogg'],
  'timer-expired': ['interface-sounds', 'error_008.ogg'],
  'plan-committed': ['interface-sounds', 'drop_002.ogg'],

  // --- money ---------------------------------------------------------------
  'stake-confirmed': ['casino-audio', 'chip-lay-1.ogg'],
  'escrow-forming': ['casino-audio', 'chips-stack-3.ogg'],
  'escrow-complete': ['casino-audio', 'chips-collide-2.ogg'],
  settlement: ['interface-sounds', 'bong_001.ogg'],
  payout: ['casino-audio', 'chips-handle-5.ogg'],

  // --- outcomes ------------------------------------------------------------
  victory: ['digital-audio', 'powerUp1.ogg'],
  defeat: ['digital-audio', 'lowDown.ogg'],
  draw: ['digital-audio', 'twoTone2.ogg'],
  'round-won': ['digital-audio', 'zapThreeToneUp.ogg'],
  champion: ['digital-audio', 'powerUp11.ogg'],
};

function fetchText(url) {
  return new Promise((resolve, reject) => {
    get(url, (res) => {
      if (res.statusCode >= 300 && res.headers.location) {
        return resolve(fetchText(res.headers.location));
      }
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

function fetchFile(url, path) {
  execSync(`curl -sSL --max-time 120 -o ${JSON.stringify(path)} ${JSON.stringify(url)}`);
}

rmSync(WORK, { recursive: true, force: true });
mkdirSync(WORK, { recursive: true });
mkdirSync(OUT, { recursive: true });

const packMeta = {};
for (const slug of Object.keys(PACKS)) {
  const page = `https://kenney.nl/assets/${slug}`;
  const html = await fetchText(page);
  const m = html.match(new RegExp(`href='(https://kenney\\.nl/media/pages/assets/${slug}/[^']*\\.zip)'`));
  if (!m) throw new Error(`no zip link found on ${page}`);
  const zip = `${WORK}/${slug}.zip`;
  console.log(`fetching ${PACKS[slug]} …`);
  fetchFile(m[1], zip);
  execSync(`unzip -oq ${JSON.stringify(zip)} -d ${JSON.stringify(`${WORK}/${slug}`)}`);
  packMeta[slug] = { name: PACKS[slug], source: page, zip: m[1] };
}

const today = new Date().toISOString().slice(0, 10);
const credits = [];
for (const [cue, [pack, file]] of Object.entries(CHOICES)) {
  const src = `${WORK}/${pack}/Audio/${file}`;
  if (!existsSync(src)) throw new Error(`missing ${src}`);
  copyFileSync(src, `${OUT}/${cue}.ogg`);
  credits.push({
    cue,
    file: `${cue}.ogg`,
    original: file,
    pack: packMeta[pack].name,
    author: 'Kenney (kenney.nl)',
    source: packMeta[pack].source,
    licence: 'CC0 1.0 (public domain)',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    retrieved: today,
  });
}

writeFileSync(
  'src/ui/sfx/audio-credits.json',
  JSON.stringify({ retrieved: today, credits }, null, 2) + '\n',
  'utf8',
);
rmSync(WORK, { recursive: true, force: true });
console.log(`wrote ${credits.length} cue files into ${OUT}/ and src/ui/sfx/audio-credits.json`);
console.log('run `npm run icons` to regenerate ASSETS_CREDITS.md with the audio section.');
