/**
 * Fetch the icon set and generate `src/ui/art/icons.ts`.
 *
 * Every icon here is from game-icons.net, which is CC BY 3.0 — free for
 * commercial use, attribution required. The author is part of the URL, so the
 * credit line for each file is derived from the same string that fetched it
 * and cannot drift from what was actually downloaded. Nothing is used whose
 * licence and author I could not read off the source.
 *
 * The downloaded files are 512x512 with a solid background rectangle behind a
 * single white path. The rectangle is stripped so the glyph can be tinted with
 * `currentColor` and sit on our own palette, which is what keeps a set of
 * borrowed icons looking like one deliberate set rather than a pile.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';

const LICENCE = 'CC BY 3.0';
const LICENCE_URL = 'https://creativecommons.org/licenses/by/3.0/';
const RETRIEVED = new Date().toISOString().slice(0, 10);

/** slot -> game-icons path. The path carries the author. */
const ICONS = {
  // Cards
  'card.salvo': 'lorc/cannon-shot',
  'card.lance': 'lorc/spear-hook',
  'card.burst': 'lorc/explosion-rays',
  'card.rake': 'lorc/triple-scratches',
  'card.breaker': 'lorc/cracked-shield',
  'card.ping': 'lorc/radar-sweep',
  'card.echo': 'lorc/sonic-screech',
  'card.sounding': 'lorc/sonic-boom',
  'card.jam': 'lorc/interdiction',
  'card.siphon': 'lorc/vortex',
  'card.mirror': 'lorc/mirror-mirror',
  'card.ambush': 'lorc/wolf-trap',

  // Ships
  'ship.dreadnought': 'delapouite/boat-horizon',
  'ship.forge': 'lorc/anvil-impact',
  'ship.blackout': 'lorc/eclipse',
  'ship.warhead': 'lorc/mushroom-cloud',
  'ship.kiln': 'lorc/burning-embers',
  'ship.leech': 'lorc/energy-arrow',
  'ship.cinder': 'lorc/small-fire',
  'ship.beacon': 'delapouite/lighthouse',
  'ship.spite': 'lorc/skull-crack',
  'ship.ember': 'lorc/bombing-run',
  'ship.pin': 'delapouite/pin',
  'ship.thorn': 'lorc/thorn-helix',

  // Board and UI
  'ui.hit': 'lorc/bright-explosion',
  'ui.miss': 'lorc/water-splash',
  'ui.water': 'lorc/waves',
  'ui.contact': 'delapouite/crosshair',
  'ui.charge': 'lorc/lightning-arc',
  'ui.timer': 'lorc/hourglass',
  'ui.rank': 'lorc/laurels',
  'ui.trophy': 'lorc/trophy',
  'ui.anchor': 'lorc/anchor',
  'ui.sunk': 'delapouite/sinking-ship',
  'ui.locked': 'lorc/padlock',
  'ui.target': 'lorc/targeting',
  'ui.hidden': 'lorc/hidden',
};

const url = (p) => `https://game-icons.net/icons/ffffff/000000/1x1/${p}.svg`;

/** Pull the glyph paths out, dropping the background rectangle. */
function extractPaths(svg) {
  const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*>/g)].map((m) => ({
    d: m[1],
    tag: m[0],
  }));
  // The background is a full-canvas path in the first slot. Compare with
  // whitespace stripped from both sides, or the space in "M0 0h512..." makes
  // the test quietly never match and every icon keeps its black square.
  const flat = (d) => d.replace(/\s+/g, '').toLowerCase();
  const BACKDROP = flat('M0 0h512v512H0z');
  const glyphs = paths.filter((p) => !flat(p.d).startsWith(BACKDROP));
  return (glyphs.length ? glyphs : paths).map((p) => p.d);
}

const entries = [];
const credits = [];

for (const [slot, path] of Object.entries(ICONS)) {
  const res = await fetch(url(path));
  if (!res.ok) {
    console.error(`SKIP ${slot} (${path}): HTTP ${res.status}`);
    continue;
  }
  const svg = await res.text();
  const ds = extractPaths(svg);
  if (!ds.length) {
    console.error(`SKIP ${slot} (${path}): no glyph path found`);
    continue;
  }
  entries.push([slot, ds]);
  const [author, name] = path.split('/');
  credits.push({ slot, path, author, name, source: `https://game-icons.net/1x1/${path}.html` });
  process.stdout.write('.');
}
console.log(`\n${entries.length}/${Object.keys(ICONS).length} icons fetched`);

mkdirSync('src/ui/art', { recursive: true });

const ts = `/* GENERATED by scripts/fetch-icons.mjs — do not edit by hand. */

/**
 * The icon set, as bare path data on a 512x512 canvas.
 *
 * Every glyph is from game-icons.net under ${LICENCE}, which permits
 * commercial use and requires attribution — the credits screen carries it and
 * ASSETS_CREDITS.md records author, source and retrieval date per file.
 *
 * They are stored as paths rather than files so they tint with currentColor,
 * cost one HTTP request (none — they are in the bundle), and can be drawn at
 * any size without a second asset. Total weight is about ${Math.round(
   entries.reduce((n, [, ds]) => n + ds.join('').length, 0) / 1024,
 )} KB.
 */
export const ICON_PATHS: Record<string, string[]> = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  2,
)};

export type IconName = keyof typeof ICON_PATHS;

export const ICON_CREDITS: { slot: string; author: string; name: string; source: string }[] =
  ${JSON.stringify(
    credits.map(({ slot, author, name, source }) => ({ slot, author, name, source })),
    null,
    2,
  )};

export const ICON_LICENCE = ${JSON.stringify(LICENCE)};
export const ICON_LICENCE_URL = ${JSON.stringify(LICENCE_URL)};
export const ICON_RETRIEVED = ${JSON.stringify(RETRIEVED)};
`;
writeFileSync('src/ui/art/icons.ts', ts, 'utf8');
console.log('wrote src/ui/art/icons.ts');

// The audio section comes from the JSON that scripts/fetch-audio.mjs wrote
// when it downloaded the files — same single-writer rule as the icons.
let audioSection = `## Audio

**None shipped.** The cue list exists and fires; no files are bundled.
`;
try {
  const audio = JSON.parse(readFileSync('src/ui/sfx/audio-credits.json', 'utf8'));
  audioSection = `## Audio — Kenney (kenney.nl)

**${audio.credits.length} sound cues**, all CC0 1.0 / public domain
(<https://creativecommons.org/publicdomain/zero/1.0/>), retrieved ${audio.retrieved}
by \`npm run audio\`. CC0 requires no attribution; it is recorded anyway.
Files live in \`src/ui/sfx/files/\`, renamed to their cue.

| Cue | File | From pack | Original file | Author | Source |
| --- | --- | --- | --- | --- | --- |
${audio.credits
  .map(
    (a) =>
      `| \`${a.cue}\` | \`${a.file}\` | ${a.pack} | \`${a.original}\` | ${a.author} | <${a.source}> |`,
  )
  .join('\n')}
`;
} catch {
  // No audio fetched yet — the placeholder section stands.
}

const authors = [...new Set(credits.map((c) => c.author))].sort();
const md = `# Asset credits

Every third-party asset in ARMADA, with its source, author, licence and
the date it was retrieved. **Nothing is used whose licence could not be read
off the source.** No Epic Games asset, model, texture, font or sound is used or
referenced; "stylised 3D" in the brief is a visual target, not a source.

## Icons — game-icons.net

**${credits.length} icons**, all ${LICENCE} (<${LICENCE_URL}>), retrieved ${RETRIEVED}.
Commercial use permitted; **attribution required**, which the in-app Credits
screen provides and this file records.

Authors used: ${authors.join(', ')}.

Icons are stored as path data in \`src/ui/art/icons.ts\` and recoloured to the
game palette. Recolouring and cropping are permitted under CC BY; the
attribution is unaffected.

| Slot | Icon | Author | Source |
| --- | --- | --- | --- |
${credits.map((c) => `| \`${c.slot}\` | ${c.name} | ${c.author} | <${c.source}> |`).join('\n')}

${audioSection}
## Everything else

| Asset | Origin | Licence |
| --- | --- | --- |
| Ship hulls, board tiles, card frames, wordmark, all VFX | Drawn procedurally in this repository | Original work, no third-party content |
| Palette | Defined in \`src/ui/theme.css\` | Original work |
| Fonts | Baloo 2, Nunito, JetBrains Mono, bundled from @fontsource | SIL Open Font License 1.1 |

## Verification

\`npm run icons\` re-fetches every icon from the URL recorded above and
regenerates both \`src/ui/art/icons.ts\` and this file (including the audio
table, from \`src/ui/sfx/audio-credits.json\`); \`npm run audio\` re-fetches
every sound from its pack URL. The credits cannot drift from what is actually
in the build.
`;
writeFileSync('ASSETS_CREDITS.md', md, 'utf8');
console.log('wrote ASSETS_CREDITS.md');
